AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  env:
    Type: String
  authRoleArn:
    Type: String
  unauthRoleArn:
    Type: String
  functionaccudappCustomMessageArn:
    Type: String
    Default: functionaccudappCustomMessageArn
  functionaccudappCustomMessageName:
    Type: String
    Default: functionaccudappCustomMessageName
  functionaccudappPostConfirmationArn:
    Type: String
    Default: functionaccudappPostConfirmationArn
  functionaccudappPostConfirmationName:
    Type: String
    Default: functionaccudappPostConfirmationName
  resourceNameTruncated:
    Type: String
  userPoolName:
    Type: String
  autoVerifiedAttributes:
    Type: CommaDelimitedList
  mfaConfiguration:
    Type: String
  mfaTypes:
    Type: CommaDelimitedList
  smsAuthenticationMessage:
    Type: String
  smsVerificationMessage:
    Type: String
  emailVerificationSubject:
    Type: String
  emailVerificationMessage:
    Type: String
  defaultPasswordPolicy:
    Type: String
  passwordPolicyMinLength:
    Type: Number
  passwordPolicyCharacters:
    Type: CommaDelimitedList
  requiredAttributes:
    Type: CommaDelimitedList
  userpoolClientGenerateSecret:
    Type: String
  userpoolClientRefreshTokenValidity:
    Type: String
  userpoolClientWriteAttributes:
    Type: CommaDelimitedList
  userpoolClientReadAttributes:
    Type: CommaDelimitedList
  userpoolClientLambdaRole:
    Type: String
  userpoolClientSetAttributes:
    Type: String
  useDefault:
    Type: String
  authSelections:
    Type: String
  resourceName:
    Type: String
  usernameAttributes:
    Type: CommaDelimitedList
  userPoolGroups:
    Type: String
  adminQueries:
    Type: String
  triggers:
    Type: String
  hostedUI:
    Type: String
  userPoolGroupList:
    Type: CommaDelimitedList
  verificationBucketName:
    Type: String
  parentStack:
    Type: String
  permissions:
    Type: CommaDelimitedList
  dependsOn:
    Type: CommaDelimitedList
Conditions:
  ShouldNotCreateEnvResources:
    Fn::Equals:
      - Ref: env
      - NONE
Resources:
  CustomMessageConfirmationBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Fn::If:
          - ShouldNotCreateEnvResources
          - Ref: verificationBucketName
          - Fn::Join:
              - ''
              - - Ref: verificationBucketName
                - '-'
                - Ref: env
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - Authorization
              - Content-Length
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            MaxAge: '3000'
  SNSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::If:
          - ShouldNotCreateEnvResources
          - accuda0f447dc6_sns-role
          - Fn::Join:
              - ''
              - - sns
                - undefined
                - Fn::Select:
                    - '3'
                    - Fn::Split:
                        - '-'
                        - Ref: AWS::StackName
                - '-'
                - Ref: env
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: cognito-idp.amazonaws.com
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: accuda0f447dc6_role_external_id
      Policies:
        - PolicyName: accuda0f447dc6-sns-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: '*'
  UserPool:
    Type: AWS::Cognito::UserPool
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName:
        Fn::If:
          - ShouldNotCreateEnvResources
          - Ref: userPoolName
          - Fn::Join:
              - ''
              - - Ref: userPoolName
                - '-'
                - Ref: env
      Schema:
        - Name: email
          Required: 'true'
          Mutable: 'true'
        - Name: family_name
          Required: 'true'
          Mutable: 'true'
        - Name: locale
          Required: 'true'
          Mutable: 'true'
        - Name: given_name
          Required: 'true'
          Mutable: 'true'
        - Name: phone_number
          Required: 'true'
          Mutable: 'true'
      LambdaConfig:
        CustomMessage:
          Ref: functionaccudappCustomMessageArn
        PostConfirmation:
          Ref: functionaccudappPostConfirmationArn
      AutoVerifiedAttributes:
        Ref: autoVerifiedAttributes
      EmailVerificationMessage:
        Ref: emailVerificationMessage
      EmailVerificationSubject:
        Ref: emailVerificationSubject
      Policies:
        PasswordPolicy:
          MinimumLength:
            Ref: passwordPolicyMinLength
          RequireLowercase: 'true'
          RequireNumbers: 'true'
          RequireSymbols: 'true'
          RequireUppercase: 'true'
      UsernameAttributes:
        Ref: usernameAttributes
      MfaConfiguration:
        Ref: mfaConfiguration
      SmsVerificationMessage:
        Ref: smsVerificationMessage
      SmsConfiguration:
        SnsCallerArn:
          Fn::GetAtt:
            - SNSRole
            - Arn
        ExternalId: accuda0f447dc6_role_external_id
    DependsOn: SNSRole
  UserPoolCustomMessageLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: UserPool
    Properties:
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName:
        Ref: functionaccudappCustomMessageName
      SourceArn:
        Fn::GetAtt:
          - UserPool
          - Arn
  UserPoolPostConfirmationLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: UserPool
    Properties:
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName:
        Ref: functionaccudappPostConfirmationName
      SourceArn:
        Fn::GetAtt:
          - UserPool
          - Arn
  accudappPostConfirmationAddToGroupCognito:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: accudappPostConfirmationAddToGroupCognito
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cognito-idp:AdminAddUserToGroup
              - cognito-idp:GetGroup
              - cognito-idp:CreateGroup
            Resource:
              Fn::GetAtt:
                - UserPool
                - Arn
      Roles:
        - Fn::Join:
            - ''
            - - accudappPostConfirmation
              - '-'
              - Ref: env
  UserPoolClientWeb:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: accuda0f447dc6_app_clientWeb
      ReadAttributes:
        Ref: userpoolClientReadAttributes
      WriteAttributes:
        Ref: userpoolClientWriteAttributes
      RefreshTokenValidity:
        Ref: userpoolClientRefreshTokenValidity
      UserPoolId:
        Ref: UserPool
    DependsOn: UserPool
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: accuda0f447dc6_app_client
      ReadAttributes:
        Ref: userpoolClientReadAttributes
      WriteAttributes:
        Ref: userpoolClientWriteAttributes
      GenerateSecret:
        Ref: userpoolClientGenerateSecret
      RefreshTokenValidity:
        Ref: userpoolClientRefreshTokenValidity
      UserPoolId:
        Ref: UserPool
    DependsOn: UserPool
  UserPoolClientRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::If:
          - ShouldNotCreateEnvResources
          - Ref: userpoolClientLambdaRole
          - Fn::Join:
              - ''
              - - upClientLambdaRole
                - undefined
                - Fn::Select:
                    - '3'
                    - Fn::Split:
                        - '-'
                        - Ref: AWS::StackName
                - '-'
                - Ref: env
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
    DependsOn: UserPoolClient
  UserPoolClientLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile:
          Fn::Join:
            - ''
            - - const response = require('cfn-response');
              - const aws = require('aws-sdk');
              - const identity = new aws.CognitoIdentityServiceProvider();
              - exports.handler = (event, context, callback) => {
              - ' if (event.RequestType == ''Delete'') { '
              - '   response.send(event, context, response.SUCCESS, {})'
              - ' }'
              - ' if (event.RequestType == ''Update'' || event.RequestType == ''Create'') {'
              - '   const params = {'
              - '     ClientId: event.ResourceProperties.clientId,'
              - '     UserPoolId: event.ResourceProperties.userpoolId'
              - '   };'
              - '   identity.describeUserPoolClient(params).promise()'
              - '     .then((res) => {'
              - '       response.send(event, context, response.SUCCESS, {''appSecret'': res.UserPoolClient.ClientSecret});'
              - '     })'
              - '     .catch((err) => {'
              - '       response.send(event, context, response.FAILED, {err});'
              - '     });'
              - ' }'
              - '};'
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: '300'
      Role:
        Fn::GetAtt:
          - UserPoolClientRole
          - Arn
    DependsOn: UserPoolClientRole
  UserPoolClientLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: accuda0f447dc6_userpoolclient_lambda_iam_policy
      Roles:
        - Ref: UserPoolClientRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cognito-idp:DescribeUserPoolClient
            Resource:
              Fn::GetAtt:
                - UserPool
                - Arn
    DependsOn: UserPoolClientLambda
  UserPoolClientLogPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: accuda0f447dc6_userpoolclient_lambda_log_policy
      Roles:
        - Ref: UserPoolClientRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              Fn::Sub:
                - >-
                  arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*
                - region:
                    Ref: AWS::Region
                  account:
                    Ref: AWS::AccountId
                  lambda:
                    Ref: UserPoolClientLambda
    DependsOn: UserPoolClientLambdaPolicy
  UserPoolClientInputs:
    Type: Custom::LambdaCallout
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - UserPoolClientLambda
          - Arn
      clientId:
        Ref: UserPoolClient
      userpoolId:
        Ref: UserPool
    DependsOn: UserPoolClientLogPolicy
  MFALambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::If:
          - ShouldNotCreateEnvResources
          - accuda0f447dc6_totp_lambda_role
          - Fn::Join:
              - ''
              - - accuda0f447dc6_totp_lambda_role
                - '-'
                - Ref: env
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: accuda0f447dc6_totp_pass_role_policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  Fn::If:
                    - ShouldNotCreateEnvResources
                    - arn:aws:iam:::role/accuda0f447dc6_totp_lambda_role
                    - Fn::Join:
                        - ''
                        - - arn:aws:iam:::role/accuda0f447dc6_totp_lambda_role
                          - '-'
                          - Ref: env
  MFALambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile:
          Fn::Join:
            - ''
            - - const response = require('cfn-response');
              - const aws = require('aws-sdk');
              - const identity = new aws.CognitoIdentityServiceProvider();
              - exports.handler = (event, context, callback) => {
              - ' if (event.RequestType == ''Delete'') { '
              - '   response.send(event, context, response.SUCCESS, {})'
              - ' }'
              - ' if (event.RequestType == ''Update'' || event.RequestType == ''Create'') {'
              - '   let totpParams = {};'
              - '   try {'
              - '     totpParams = {'
              - '       UserPoolId: event.ResourceProperties.userPoolId,'
              - '       MfaConfiguration: event.ResourceProperties.mfaConfiguration,'
              - '       SmsMfaConfiguration: {'
              - '         SmsAuthenticationMessage: event.ResourceProperties.smsAuthenticationMessage,'
              - '         SmsConfiguration: {'
              - '           SnsCallerArn: event.ResourceProperties.smsConfigCaller,'
              - '           ExternalId: event.ResourceProperties.smsConfigExternalId'
              - '         }'
              - '       },'
              - '       SoftwareTokenMfaConfiguration: {Enabled: event.ResourceProperties.totpEnabled.toLowerCase() === ''true'' ? true : false}'
              - '     };'
              - '   } catch(e) {'
              - '     response.send(event, context, response.FAILED, {e});'
              - '   };'
              - '   identity.setUserPoolMfaConfig(totpParams).promise()'
              - '     .then((res) => {'
              - '       response.send(event, context, response.SUCCESS, {res});'
              - '     })'
              - '     .catch((err) => {'
              - '       response.send(event, context, response.FAILED, {err});'
              - '     });'
              - ' }'
              - '};'
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: '300'
      Role:
        Fn::GetAtt:
          - MFALambdaRole
          - Arn
    DependsOn: MFALambdaRole
  MFALambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: accuda0f447dc6_totp_lambda_iam_policy
      Roles:
        - Fn::If:
            - ShouldNotCreateEnvResources
            - accuda0f447dc6_totp_lambda_role
            - Fn::Join:
                - ''
                - - accuda0f447dc6_totp_lambda_role
                  - '-'
                  - Ref: env
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cognito-idp:SetUserPoolMfaConfig
            Resource:
              Fn::GetAtt:
                - UserPool
                - Arn
    DependsOn: MFALambda
  MFALogPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: accuda0f447dc6_totp_lambda_log_policy
      Roles:
        - Fn::If:
            - ShouldNotCreateEnvResources
            - accuda0f447dc6_totp_lambda_role
            - Fn::Join:
                - ''
                - - accuda0f447dc6_totp_lambda_role
                  - '-'
                  - Ref: env
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              Fn::Sub:
                - >-
                  arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*
                - region:
                    Ref: AWS::Region
                  account:
                    Ref: AWS::AccountId
                  lambda:
                    Ref: MFALambda
    DependsOn: MFALambdaPolicy
  MFALambdaInputs:
    Type: Custom::LambdaCallout
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - MFALambda
          - Arn
      userPoolId:
        Ref: UserPool
      mfaConfiguration:
        Ref: mfaConfiguration
      totpEnabled: 'true'
      smsConfigCaller:
        Fn::GetAtt:
          - SNSRole
          - Arn
      smsAuthenticationMessage:
        Ref: smsAuthenticationMessage
      smsConfigExternalId: accuda0f447dc6_role_external_id
    DependsOn: MFALogPolicy
Outputs:
  UserPoolId:
    Value:
      Ref: UserPool
    Description: Id for the user pool
  UserPoolName:
    Value:
      Ref: userPoolName
  AppClientIDWeb:
    Value:
      Ref: UserPoolClientWeb
    Description: The user pool app client id for web
  AppClientID:
    Value:
      Ref: UserPoolClient
    Description: The user pool app client id
  AppClientSecret:
    Value:
      Fn::GetAtt:
        - UserPoolClientInputs
        - appSecret
  CreatedSNSRole:
    Value:
      Fn::GetAtt:
        - SNSRole
        - Arn
    Description: role arn
